# Site settings
title: Francesca Mereu
email: martech.platform@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This a FabAcademy 2015 website. There are all processes of my work, experiments, 
  prototypes..
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: M-Artech
github_username:  mereufrance77

# Build settings
markdown: kramdown
